name: fitness
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase Core & Auth
  firebase_core: ^3.15.1
  firebase_auth: any
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.12

  # HTTP & OpenAI/Groq integration
  http: ^1.2.1
  flutter_dotenv: ^5.1.0

  # InBody Image Upload
  image_picker: ^1.0.7
  firebase_storage: ^12.4.9
  image: ^4.1.3 # ✅ For resizing image before base64 encoding

  # Path for file paths
  path: ^1.9.0

  # ✅ Added for saving workout stats like streak and minutes
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # ✅ Step 1: Added icon generator

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.png
    - .env

# ✅ Step 1: Launcher icon config
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
